---
  - name: Stop opscenter
    service: name=opscenter state=stopped

  - name: Start opscenter
    service: name=opscenter state=started

  - name: Restart opscenter
    service: name=opscenter state=restarted
